Feature/auth login
se761group2/industry-4 pull request #47
Opened 2020-09-25 02:40 UTC by Deagler

## GitHub Issue Solved:

closes #6 

## Current behaviour

There was no login/register

## Changed behaviour

- Added FirebaseUI to the frontend (using Google OAuth for now for speed of development)
- Added a useUserContext custom hook to get firebase user credentials
- Added a user detail + log out button to the navigation bar
- Backend now parses the user id from the Authorization header. 

**This means you need to set LOCAL_MOCK_USER in api/functions/.env** (only if you want to use the GraphQL Playground) The current user ID there is my user id.

## PR checklist

Remember to check the following

 - [ ] Tag specific people to review your PR
 - [ ] Update the ReadMe with any new run instructions
 - [ ] Closes the associated issue (if applicable)

## Notes

### Demo

### Run instructions

2020-09-25 23:52 UTC, FrankWangma requested changes
Everything looks good to me for the most part.
Just one part which isn't really an issue, but more of a QoL change: 
- The logout button immediately logs the user out. I was wondeing if we should have like a prompt, to ask whether or not the user wants to log out just in case they accidentally clicked the button

2020-09-27 22:47 UTC, merw957 commented on app/src/components/Heading.tsx
> +                    <IonBackButton />
The back button isn't showing up for me. I think you need to put the <IonButton> thing around this again for it to work.

2020-09-27 22:57 UTC, merw957 commented on app/src/components/Heading.tsx
> +                        <IonTitle className="text-center text-2xl font-heading">
Also need to put the font back on this title

2020-09-27 23:09 UTC, FrankWangma approved these changes
Looking good to me now

2020-09-27 23:11 UTC, merged