Allow users to add machines
se761group2/industry-4 pull request #48
Opened 2020-09-25 06:31 UTC by Deagler

**Review this PR After #47 **

## GitHub Issue Solved:

closes #26 

## Current behaviour

- users cant add machines

## Changed behaviour

- users can add machines via a modal on the main page.

## PR checklist

Remember to check the following

 - [ ] Tag specific people to review your PR
 - [ ] Update the ReadMe with any new run instructions
 - [ ] Closes the associated issue (if applicable)

## Notes

![image](https://user-images.githubusercontent.com/6028185/94234121-27067f00-ff5d-11ea-8cba-4574b733c676.png)

### Demo

### Run instructions

2020-09-27 22:37 UTC, FrankWangma approved these changes
Adding machine works.
May require some integration with the other PRs at a later time

2020-09-27 23:14 UTC, FrankWangma approved these changes
Integration changes have been added. LGTM

2020-09-27 23:21 UTC, merw957 requested changes
Just left a comment about the changes to the HealthContainer and LineGraph files. Looks good overall though 👍

2020-09-27 23:21 UTC, merw957 commented on app/src/components/HealthContainer.tsx
> +            <div className={`rounded-lg shadow-xl font-bold text-lg w-full flex-grow bg-${bg}-550`}>
This change messes up the formatting for the sensors and individual sensor pages. Is there a reason this was changed?

2020-09-27 23:21 UTC, merw957 commented on app/src/components/LineGraph.tsx
> +            <div className="bg-white rounded-lg items-center pt-4 pb-4 max-w-lg flex-grow">
Same here

2020-09-28 00:21 UTC, merw957 approved these changes
Formatting issues are fixed + fixes back button bug. LGTM 👍

2020-09-28 00:21 UTC, merged