Loaders for GraphQL Queries
se761group2/industry-4 pull request #70
Opened 2020-10-01 04:04 UTC by Deagler

## GitHub Issue Solved:

closes #54 

## Current behaviour

It shows "no items" when it is actually just loading the items.

## Changed behaviour

Now it shows a spinner while loading. No items when there are actually no items. And the content when there is content to be shown.

## PR checklist

Remember to check the following

 - [ ] Tag specific people to review your PR
 - [ ] Update the ReadMe with any new run instructions
 - [ ] Closes the associated issue (if applicable)
 - [ ] Updated kanban board

## Notes

### Demo

### Run instructions

2020-10-01 09:14 UTC, merw957 requested changes
Spinners looking good. Not sure if it's just me, but when I go to a machine with no sensors (for example the machine  i just added with moderate health called "no sensors"), it shows the spinner but once it's loaded it doesn't show "There are no sensors for this machine", just a blank page. Might be the same issue with the machines page, but I'm not gonna delete all the machines to check lol.

2020-10-03 10:09 UTC, margeobur commented
I've fixed the no-sensors and no-machines messages not showing @merw957  :)

2020-10-03 10:43 UTC, merw957 approved these changes
LGTM 👍

2020-10-03 10:47 UTC, merged

2020-10-04 03:34 UTC, Deagler commented
Thanks for fixing that @margeobur